server:
  address: "127.0.0.1"
  port: 8080

ffmpeg-params:
  ffmpeg-binary: "ffmpeg"
  ffprobe-binary: "ffprobe"

file-system-navigator-params:
  default-start-directory: ""

global-video-encoding-params:
  codec: "libx264"
  profile: "main"
  preset: "veryfast"
  framerate: 25
  keyframes: 200
  pixel-format: "yuv420p"
  encoding-timeout: 5
  concurrent-jobs: 2

global-audio-encoding-params:
  codec: "aac"
  bitrate: "192k"
  channels: 2
  sample-rate: 44100
  encoding-timeout: 5
  concurrent-jobs: 2
  overhead-duration: 1

segment-params:
  dash-file-name: "dash.mpd"
  dash-output-path: "dash"
  chunk-output-path: "chunks"
  duration: 10
  lifetime: 120
  encoding-timeout: 5

export-params:
  path: "export"
