server:
  address: "127.0.0.1"
  port: 5000

ffmpeg-params:
  ffmpeg-binary: "ffmpeg"
  ffprobe-binary: "ffprobe"

file-system-navigator-params:
  default-start-directory: ""

global-video-encoding-params:
  codec: "libx264"
  profile: "main"
  preset: "veryfast"
  framerate: 25
  keyframes: 200
  pixel-format: "yuv420p"
  encoding-timeout: 5
  concurrent-jobs: 2

global-audio-encoding-params:
  codec: "aac"
  bitrate: "192k"
  channels: 2
  sample-rate: 48000
  encoding-timeout: 5
  concurrent-jobs: 2
  overhead-duration: 1

segment-params:
  dash-file-name: "dash.mpd"
  dash-output-path: "dash"
  chunk-output-path: "chunks"
  #target segment duration
  duration: 10
  #minimum amount of seconds containing integer number of audio AND video frames
  #for video framerate 25 fps and audio sample rate 48000 Hz it equals 0.32 seconds
  #0.32s = 8 video frames
  #0.32s = 15 AAC frames
  av-frame-duration: 0.32
  lifetime: 120
  encoding-timeout: 5

export-params:
  path: "export"
  frames-compression-level: 100
  frames-preview-quality: 12
  frames-preview-size: 320
