name: Build, package, release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build
      run: cd scripts && ./build_release.sh && cd ..

    - name: Save linux-amd64
      uses: actions/upload-artifact@v2
      with:
        name: linux-amd64
        path: release/linux-amd64.tar.gz
    - name: Save linux-arm64
      uses: actions/upload-artifact@v2
      with:
        name: linux-arm64
        path: release/linux-arm64.tar.gz
    - name: Save mac-amd64
      uses: actions/upload-artifact@v2
      with:
        name: mac-amd64
        path: release/mac-amd64.tar.gz
    - name: Save windows-amd64
      uses: actions/upload-artifact@v2
      with:
        name: windows-amd64
        path: release/windows-amd64.tar.gz
